### ISSUE TITLE
Incremental Data Processing with Hudi Failing

### ISSUE THREAD

**Issue by vayu068** [aws-samples/data-engineering-for-aws-immersion-day#27] opened 2022-10-09 18:39 UTC
S3 holding Dependent jars isn't accesible. Please find below error logs
LAUNCH ERROR | Error downloading from S3 for bucket: aws-dataengineering-day.workshop.aws, key: hudijars/calcite-core-1.10.0.jar.Access Denied (Service: Amazon S3; Status Code: 403; Please refer logs for details.

**Comment by melodyyangaws** [comment] 2022-10-12 11:22
it should be OK now. please try again and please let me know if you still can't access it.

**Comment by tomaszdudek7** [comment] 2022-10-19 09:53
@melodyyangaws We've tried running this recently with @Ivnnk (i.e. yesterday) and [the 12th point in Step 1](https://catalog.us-east-1.prod.workshops.aws/workshops/976050cc-0606-4b23-b49f-ca7b8ac4b153/en-US/600/615-glue-hudi-lab) is what makes the job fail. There's no access to that bucket.

**Comment by melodyyangaws** [comment] 2022-10-19 23:55
Thanks for the details @tomaszdudek7 . that's really helpful for us to locate the root cause. The permission issue is fixed now. please give it a try with the updated CFN template or manually add the s3 bucket permission to your GlueLabRole in your existing lab environment. You can see the detail in the PR request.

**Closed as completed by melodyyangaws** 2022-10-19 23:55 UTC

**Comment by IVnnk** [comment] 2022-10-21 09:55
I can confirm everything works. Thanks!
